### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by Vaelatern** [quozl/netrek-client-cow#2]
The release 3.3.1 as downloadable from the netrek website can't build, it has multiple issues (Doesn't seem to recognize the latest GMP as being GMP) and none of the changes since 2012.

Thank you!

**Comment by Vaelatern** [comment]
HEAD doesn't get past configure either, build logs at: https://travis-ci.org/github/void-linux/void-packages/jobs/685893646

A cross building attempt, same error: https://travis-ci.org/github/void-linux/void-packages/jobs/685893650#L4158-L4306

**Comment by quozl** [comment]
Thanks for testing.

**Comment by quozl** [comment]
Your first build logs look like 3.3.1 tarball and not HEAD.  Are you sure it is HEAD?  The error is caused by missing local key.  I suspect we have since ripped out the verification infrastructure, or at least disabled it.

**Comment by Vaelatern** [comment]
It's a 3.3.1 tarball then patched with `git diff 5fa2a6b5b407c61217de8cb584a4932b7650e884..@`

**Comment by quozl** [comment]
Oh, I see now, thanks.  I guess that won't work because removed files aren't removed.  key.mk.in for instance.

I've tagged a release, see https://github.com/quozl/netrek-client-cow/releases

**Comment by Vaelatern** [comment]
Thank you!
