### ISSUE TITLE
Build instructions need updating? No ./configure script

### ISSUE THREAD

**Issue by ghost** [quozl/netrek-client-cow#5]
I tried running autoconf, but got an error. I'm lost on how to continue.

```
[ram@rams-imac netrek-client-cow]$ ./configure
bash: ./configure: No such file or directory
[ram@rams-imac netrek-client-cow]$ autoconf 
configure.ac:189: error: possibly undefined macro: AM_PATH_SDL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:190: error: possibly undefined macro: AM_CONDITIONAL
[ram@rams-imac netrek-client-cow]$ ./configure
configure: error: cannot run /bin/sh ./config.sub
```

**Comment by kwadroke** [comment]
autogen.sh creates the configure script. 
You might want to post the "autoconf" error as well as OS information

**Comment by quozl** [comment]
Undefined macro for AM_PATH_SDL means SDL is not installed.  These sources are not in a distribution form.  `configure` is created by `autogen.sh` when using a git clone, and is included in the tarball when using "make dist".

**Comment by ghost** [comment]
Got it to build. Thanks all. Sorry for not reading INSTALL closely enough :)
